package br.ufmt.ic.paw2.entities;
// Generated 29/04/2016 21:49:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PacienteContato generated by hbm2java
 */
@Entity
@Table(name="paciente_contato"
    ,catalog="sisden"
)
public class PacienteContato  implements java.io.Serializable {


     private int pacienteId;
     private Paciente paciente;
     private String email;
     private String telefone;
     private String celular;

    public PacienteContato() {
    }

	
    public PacienteContato(Paciente paciente, String email) {
        this.paciente = paciente;
        this.email = email;
    }
    public PacienteContato(Paciente paciente, String email, String telefone, String celular) {
       this.paciente = paciente;
       this.email = email;
       this.telefone = telefone;
       this.celular = celular;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="paciente"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="Paciente_id", unique=true, nullable=false)
    public int getPacienteId() {
        return this.pacienteId;
    }
    
    public void setPacienteId(int pacienteId) {
        this.pacienteId = pacienteId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    
    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="telefone")
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="celular")
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }




}


