package br.ufmt.ic.paw2.entities;
// Generated 29/04/2016 21:49:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name="paciente"
    ,catalog="sisden"
)
public class Paciente  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Long rg;
     private Long cpf;
     private String sexo;
     private String endereco;
     private String dentistaContato;
     private PacienteContato pacienteContato;

    public Paciente() {
    }

    public Paciente(String nome, Long rg, Long cpf, String sexo, String endereco, String dentistaContato, PacienteContato pacienteContato) {
       this.nome = nome;
       this.rg = rg;
       this.cpf = cpf;
       this.sexo = sexo;
       this.endereco = endereco;
       this.dentistaContato = dentistaContato;
       this.pacienteContato = pacienteContato;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nome")
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="rg")
    public Long getRg() {
        return this.rg;
    }
    
    public void setRg(Long rg) {
        this.rg = rg;
    }

    
    @Column(name="cpf")
    public Long getCpf() {
        return this.cpf;
    }
    
    public void setCpf(Long cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="sexo")
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    
    @Column(name="endereco")
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="Dentista_Contato")
    public String getDentistaContato() {
        return this.dentistaContato;
    }
    
    public void setDentistaContato(String dentistaContato) {
        this.dentistaContato = dentistaContato;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="paciente")
    public PacienteContato getPacienteContato() {
        return this.pacienteContato;
    }
    
    public void setPacienteContato(PacienteContato pacienteContato) {
        this.pacienteContato = pacienteContato;
    }




}


